version: '3.8'

services:
  web:
    build: .
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
      - ./uploads:/var/www/html/uploads
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=sap_logs
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d

volumes:
  pgdata: